backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: '/src/assets/images/uploads'
public_folder: '/assets/images/uploads'

collections:
  - name: 'blog'
    label: 'Blog Posts'
    folder: 'src/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          hint: 'Shown as preview in archive, used for meta data.'
        }

      # Discover section
      - label: 'Discover'
        name: 'discover'
        widget: 'object'
        hint: 'Optional: different title and description for search engines and social media previews.'
        fields:
          - {
              label: 'Title',
              name: 'title',
              widget: 'string',
              hint: 'Title used for SEO and social media preview.'
            }
          - {
              label: 'Description',
              name: 'description',
              widget: 'text',
              hint: 'Short description used for SEO and social media preview.'
            }

      - {label: 'Date', name: 'date', widget: 'datetime'}
      - {label: 'Featured Image', name: 'image', widget: 'image'}
      - {label: 'Alt Text', name: 'alt', widget: 'string'}

      - label: 'Show Featured'
        name: 'showFeatured'
        widget: 'boolean'
        default: true
        hint: 'Whether or not to display the image featured in the post. Defaults to being the preview image in archives.'

      - label: 'Gallery'
        name: 'gallery'
        widget: 'list'
        collapsed: true
        hint: 'Add images for the gallery. Each image should have an alt text.'
        fields:
          - {label: 'Image', name: 'image', widget: 'image'}
          - {label: 'Alt Text', name: 'alt', widget: 'string'}

      - label: 'Google Drive Videos'
        name: 'videosGoogleDrive'
        widget: 'list'
        collapsed: true
        hint: 'Add Google Drive videos using their unique slug and label.'
        fields:
          - {label: 'Slug', name: 'slug', widget: 'string'}
          - {label: 'Label', name: 'label', widget: 'string'}

      - label: 'YouTube Videos'
        name: 'videosYouTube'
        widget: 'list'
        collapsed: true
        hint: 'Add YouTube videos using their slug (ID) and label.'
        fields:
          - {label: 'Slug', name: 'slug', widget: 'string'}
          - {label: 'Label', name: 'label', widget: 'string'}

      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        multiple: true
        hint: 'Select relevant tags for this post.'
        options:
          - Altre attività
          - Stampa
          - Attività per Disabilità
          - Formazione
          - Eventi

  - name: 'pages' # Collection for pages
    label: 'Pages'
    folder: 'src/pages'
    create: true # Allows creation of new pages
    slug: '{{slug}}'
    fields:
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Description', name: 'description', widget: 'text'}

      # Discover section for SEO purposes
      - label: 'Discover'
        name: 'discover'
        widget: 'object'
        collapsed: true
        hint: 'Optional: different title and description for search engines and social media previews.'
        fields:
          - {
              label: 'Title',
              name: 'title',
              widget: 'string',
              hint: 'Title used for SEO and social media preview.'
            }
          - {
              label: 'Description',
              name: 'description',
              widget: 'text',
              hint: 'Description used for SEO and social media preview.'
            }

      - label: 'Gallery'
        name: 'gallery'
        widget: 'list'
        collapsed: true
        hint: 'Add images for the gallery. Each image should have an alt text.'
        fields:
          - {label: 'Image', name: 'image', widget: 'image'}
          - {label: 'Alt Text', name: 'alt', widget: 'string'}
